CREATE TABLE WEB_STUDENT(
	STU_ID NUMBER PRIMARY KEY,
	STU_NAME VARCHAR2(50),
	STU_SCORE1 NUMBER,
	STU_SCORE2 NUMBER,
	STU_SUBJECT VARCHAR2(100)
);

INSERT INTO WEB_STUDENT
VALUES(1, '제우스', 90, 95, 'IT');

INSERT INTO WEB_STUDENT
VALUES(2, '포세이돈', 100, 53, 'IT');

INSERT INTO WEB_STUDENT
VALUES(3, '하데스', 90, 59, '컴공');

INSERT INTO WEB_STUDENT
VALUES(4, '오르페우스', 30, 55, 'IT');

INSERT INTO WEB_STUDENT
VALUES(5, '헤라', 77, 50, '컴공');

INSERT INTO WEB_STUDENT
VALUES(6, '에로스', NULL, NULL, '컴공');

SELECT STU_ID, SUM(STU_SCORE1 + STU_SCORE2) 
FROM WEB_STUDENT
GROUP BY STU_ID
HAVING SUM(STU_SCORE1 + STU_SCORE2) > 100
ORDER BY STU_ID;


SELECT * FROM EMPLOYEES;

SELECT JOB_ID 부서, AVG(SALARY) "평균 급여"
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '515%'
GROUP BY JOB_ID
ORDER BY "평균 급여" DESC;







