SELECT 
	LAST_NAME || ' ' || FIRST_NAME 이름,
	SALARY,
	CASE
			WHEN SALARY >= 5000 THEN 'HIGH'
			WHEN SALARY >= 3000 THEN 'MEDIUM'	
		END AS SALARY_grade
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT
	LAST_NAME || ' ' || FIRST_NAME 이름,
	DEPARTMENT_ID 부서,
	SALARY 기존급여,
	CASE WHEN DEPARTMENT_ID = 50 THEN SALARY * 0.9
		 WHEN DEPARTMENT_ID = 80 THEN SALARY * 1.1
		 ELSE SALARY
		 END AS 조정급여
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;

SELECT
	LAST_NAME || ' ' || FIRST_NAME 이름,
	DEPARTMENT_ID 부서,
	SALARY 기존급여,
	CASE DEPARTMENT_ID
		WHEN 50 THEN SALARY * 0.9
		WHEN 80 THEN SALARY * 1.1
		ELSE SALARY
		END AS 조정급여
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;

SELECT * FROM EMPLOYEES;

SELECT
	EMPLOYEE_ID 사원번호,
	LAST_NAME || ' ' || FIRST_NAME 이름,
	COMMISSION_PCT 커미션,
	SALARY 기존급여,
	CASE WHEN COMMISSION_PCT IS NULL THEN SALARY + 100
		ELSE SALARY + (SALARY * COMMISSION_PCT)
		END AS 조정급여
FROM EMPLOYEES
ORDER BY 조정급여;

SELECT
	EMPLOYEE_ID 사원번호,
	LAST_NAME || ' ' || FIRST_NAME 이름,
	COMMISSION_PCT 커미션,
	SALARY 기존급여,
	NVL2(COMMISSION_PCT, SALARY + (SALARY * COMMISSION_PCT), SALARY + 100) 최종급여
FROM EMPLOYEES
ORDER BY 커미션;

SELECT
	ROWNUM,
	E1.*,
	CASE WHEN ROWNUM BETWEEN 1 AND 5 THEN '상'
		 WHEN ROWNUM BETWEEN 6 AND 10 THEN '중'
		 ELSE '하'
		 END AS 비고
FROM (SELECT EMPLOYEE_ID 사원번호,
	LAST_NAME || ' ' || FIRST_NAME 이름,
	COMMISSION_PCT 커미션,
	SALARY
	FROM EMPLOYEES
	ORDER BY SALARY DESC) E1;

	
	
	
	
	
	
	CASE WHEN ROWNUM BETWEEN 1 AND 5 THEN '상'
		 WHEN ROWNUM BETWEEN 6 AND 10 THEN '중'
		 ELSE '하'
		 END AS 비고
FROM EMPLOYEES
ORDER BY SALARY DESC;







