--사용자 정보를 저장하는 유저 테이블


CREATE SEQUENCE WEB_SEQ_USER;


-- 사용자 번호, 아이디, 패스워드, 이름, 나이, 성별, 생일
CREATE TABLE WEB_TBL_USER(
   USER_NUMBER NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_ID VARCHAR2(1000),
   USER_PASSWORD VARCHAR2(1000),
   USER_NAME VARCHAR2(1000),
   USER_AGE NUMBER,
   USER_GENDER CHAR(1) DEFAULT 'N',
   USER_BIRTH DATE
);

SELECT * FROM WEB_TBL_USER;

INSERT INTO WEB_TBL_USER VALUES(WEB_SEQ_USER.NEXTVAL, 'aaa', '1234', '홍길동', 20, 'M', '20000101');







